name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build executable with PyInstaller (Folder Mode)
      run: |
        # 使用文件夹模式，启动更快
        pyinstaller --name="遗传改良系统" `
          --windowed `
          --add-data="config;config" `
          --add-data="templates;templates" `
          --add-data="docs;docs" `
          --add-data="*.mp4;." `
          --add-data="*.jpg;." `
          --add-data="*.ico;." `
          --hidden-import="pandas" `
          --hidden-import="pandas._libs" `
          --hidden-import="pandas._libs.tslibs.timedeltas" `
          --hidden-import="numpy" `
          --hidden-import="numpy.core._multiarray_umath" `
          --hidden-import="openpyxl" `
          --hidden-import="xlrd" `
          --hidden-import="xlsxwriter" `
          --hidden-import="matplotlib" `
          --hidden-import="matplotlib.pyplot" `
          --hidden-import="matplotlib.backends.backend_qt5agg" `
          --hidden-import="seaborn" `
          --hidden-import="scipy" `
          --hidden-import="scipy.special._ufuncs_cxx" `
          --hidden-import="scipy.stats" `
          --hidden-import="sklearn" `
          --hidden-import="sklearn.utils._weight_vector" `
          --hidden-import="sklearn.preprocessing" `
          --hidden-import="sklearn.neighbors._typedefs" `
          --hidden-import="sklearn.tree._tree" `
          --hidden-import="sklearn.ensemble._forest" `
          --hidden-import="joblib" `
          --hidden-import="PyQt6" `
          --hidden-import="PyQt6.sip" `
          --hidden-import="sqlalchemy" `
          --hidden-import="sqlalchemy.sql.default_comparator" `
          --hidden-import="cv2" `
          --hidden-import="PIL" `
          --hidden-import="PIL.Image" `
          --hidden-import="networkx" `
          --hidden-import="dateutil" `
          --hidden-import="requests" `
          --hidden-import="cryptography" `
          --hidden-import="cffi" `
          --hidden-import="pptx" `
          --hidden-import="gui.main_window" `
          --hidden-import="gui.login_dialog" `
          --hidden-import="gui.splash_screen" `
          --hidden-import="core.data.uploader" `
          --hidden-import="core.breeding_calc" `
          --hidden-import="core.breeding_calc.traits_calculation" `
          --hidden-import="core.grouping.group_manager" `
          --hidden-import="core.matching.complete_mating_executor" `
          --hidden-import="core.inbreeding.inbreeding_page" `
          --hidden-import="utils.file_manager" `
          --hidden-import="config.settings" `
          --paths="." `
          --collect-all="gui" `
          --collect-all="core" `
          --collect-all="utils" `
          --collect-all="config" `
          --clean `
          main.py
      continue-on-error: true
    
    - name: Create release directory
      run: |
        mkdir release
        # 复制可执行文件
        if (Test-Path "dist\遗传改良系统.exe") {
          Copy-Item -Path "dist\遗传改良系统.exe" -Destination "release\"
        } elseif (Test-Path "dist\遗传改良系统\遗传改良系统.exe") {
          Copy-Item -Path "dist\遗传改良系统\*" -Destination "release\" -Recurse
        }
        # 复制必要的配置和模板文件
        Copy-Item -Path "config" -Destination "release\config" -Recurse -ErrorAction SilentlyContinue
        Copy-Item -Path "templates" -Destination "release\templates" -Recurse -ErrorAction SilentlyContinue
        Copy-Item -Path "README.md" -Destination "release\" -ErrorAction SilentlyContinue
        Copy-Item -Path "docs\用户手册.md" -Destination "release\" -ErrorAction SilentlyContinue
    
    - name: Create zip archive
      run: |
        Compress-Archive -Path "release\*" -DestinationPath "genetic_improve_system_win64.zip"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: genetic-improve-system-windows
        path: genetic_improve_system_win64.zip
    
    # 暂时注释掉自动创建Release，避免权限问题
    # - name: Create Release
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     tag_name: v${{ github.run_number }}
    #     name: Release Build ${{ github.run_number }}
    #     body: |
    #       自动构建版本 #${{ github.run_number }}
    #       
    #       更新内容：
    #       - 完善个体选配功能：肉牛标记和递进机制
    #       - 修复肉牛标记逻辑
    #       - 实现真正的递进分配机制
    #       - 添加推荐矩阵保存功能
    #       - 改进分组同步机制
    #       
    #       下载后解压即可使用。
    #     files: genetic_improve_system_win64.zip
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}